---
bot:
  nick: huelightbot
  password: oauth_password_here
  port: 6667
  server: irc.chat.twitch.tv
  cheer_floor: 200
  hue_group: 4
  channel: '#your_twitch_username'
  largecheer: 1000
  off_floor: 5000
  on_floor: 500
  alerts:
    cheer: "loop"
    prime: "none"
    sub_1000: "none"
    sub_2000: "loop"
    sub_3000: "loop"
  permissions:
    setcolor: "mod"
