---
bot:
  nick: huelightbot
  password: oauth_password_here
  port: 6667
  server: irc.chat.twitch.tv
  cheer_floor: 200
  hue_group: 4
  channel: '#your_twitch_username'
  off_floor: 5000
  on_floor: 500
